
name = "opencern-cli-auth"
main = "src/index.ts"
compatibility_date = "2024-01-01"

# KV namespace for auth codes
[[kv_namespaces]]
binding = "CLI_AUTH_CODES"
id = "61434a385d3a4ec59bb5f823b5059586"
preview_id = "61434a385d3a4ec59bb5f823b5059586"

# Environment variables
[vars]
# JWT_SECRET is set as a secret: wrangler secret put JWT_SECRET

